### ISSUE TITLE
Temporary marketplace plugin

### ISSUE THREAD

**Issue by sergeylaptev** [mrmlnc/vscode-postcss-sorting#40]
Hello, @mrmlnc! I like your plugin but it seems out of date:-/ I've made temporary duplicate of your plugin and bumped its version to 2.1.1. The only change is using new version of PostCSS-sorting (2.0.1). I'll delete it as soon as you will update the original plugin:) [Link](https://marketplace.visualstudio.com/items?itemName=sergeylaptev.vscode-postcss-sorting)

**Comment by mrmlnc** [comment]
Closed by https://github.com/mrmlnc/vscode-postcss-sorting/releases/tag/2.2.0

**Comment by sergeylaptev** [comment]
Would be great if you will update GIF demo as well:) New version has different [settings syntax ](https://github.com/hudochenkov/postcss-sorting#order)

**Comment by mrmlnc** [comment]
:+1:

**Comment by mrmlnc** [comment]
@sergeylaptev, may be add you to this repository? 😄

**Comment by mrmlnc** [comment]
Should be resolved by `2.2.1`.

**Comment by sergeylaptev** [comment]
Yep, works fine to me. Looks sad without GIF though:)
