### ISSUE TITLE
Question: Any plans to use PostCSS Sorting 2.x.x anytime soon?

### ISSUE THREAD

**Issue by pawelgrzybek** [mrmlnc/vscode-postcss-sorting#41]
⬆️   ⬆️   ⬆️   ⬆️   ⬆️   ⬆️

Thanks 😊

**Comment by mrmlnc** [comment]
Thanks for reporting I'll update this plugin today😅

Closed as duplicate of https://github.com/mrmlnc/vscode-postcss-sorting/issues/40
