### ISSUE TITLE
After migration to postcss-sorting 2.x.x

### ISSUE THREAD

**Issue by pawelgrzybek** [mrmlnc/vscode-postcss-sorting#42]
After migration to postcss-sorting 2.x.x the documentation isn't correct anymore. Gif needs to be changed and options object show properties from 1.x.x. Example of settings for version 2.x.x:

```json
{
  "postcssSorting": {
    "order": [
      "custom-properties",
      "dollar-variables",
      "declarations",
      "at-rules",
      "rules"
    ],
    "properties-order": ["display", "position", "top", "right", "bottom", "left"]
  }
}
```

Happy to PR if you want...

**Comment by mrmlnc** [comment]
Should be resolver by `2.2.1`.
