### ISSUE TITLE
No keyboard shortcut command

### ISSUE THREAD

**Issue by nmsmith22389** [mrmlnc/vscode-postcss-sorting#44]
There is currently no keyboard shortcut command for sorting visible in the keybindings list of available commands. In addition, binding `postcssSorting.sort` to a command does nothing. Can you please fix this?

**Comment by mrmlnc** [comment]
You can to add the keybinding manually - https://github.com/mrmlnc/vscode-postcss-sorting#keyboard-shortcuts

**Comment by nmsmith22389** [comment]
Nevermind it just started working all of a sudden... there must have been a key conflict or something. Thanks!
