### ISSUE TITLE
Support external file for sorting configuration

### ISSUE THREAD

**Issue by wfortin** [mrmlnc/vscode-postcss-sorting#45]
Similar to the [Atom plugin](https://github.com/lysyi3m/atom-postcss-sorting), it would be great if you supported a `.postcss-sorting.json` at the root of the project.

**Comment by mrmlnc** [comment]
@wfortin,

Now you can use https://github.com/mrmlnc/vscode-postcss-sorting/releases/tag/2.3.0 with https://github.com/mrmlnc/vscode-postcss-sorting#options.

**Comment by Darkbish** [comment]
can this supported a .postcss-sorting.js file at the root of the project?

**Comment by thats4shaw** [comment]
I'd be interested to know that as well @Darkbish.

**Comment by mrmlnc** [comment]
You can try :)

By default we support https://github.com/mrmlnc/vscode-postcss-sorting/blob/master/src/extension.ts#L13-L24, but I don't know how it works with multi-root projects.
