### ISSUE TITLE
Auto sort on save?

### ISSUE THREAD

**Issue by kurtextrem** [mrmlnc/vscode-postcss-sorting#67]
Is there any way to do this?

**Comment by Swiftwork** [comment]
@kurtextrem you should make sure to search through previously closed issues first before posting a new one. Especially when there are so few (at the time of writing 10). Check out issue #19.

**Comment by mrmlnc** [comment]
Closed for #19. Will be soon. Most likely in this week.

**Comment by kurtextrem** [comment]
@Swiftwork exactly what I did, but I've only searched closed issues and overlooked the opened one. I'm sorry.

**Comment by Swiftwork** [comment]
@kurtextrem Haha no worries, however issue #19 was just re-opened 13:51 2017-05-02, partially due to this, your issue.
