### ISSUE TITLE
Not working with last VSCode versions (at least)

### ISSUE THREAD

**Issue by ghost** [mrmlnc/vscode-postcss-sorting#69]
In dev tools I'm getting those errors after trying to run sorting:

> [Extension Host] rejected promise not handled within 1 second
h.logExtensionHostMessage @ extensionHost.ts:320
(anonymous) @ extensionHost.ts:176
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
shell.ts:443 No one parser could not parse file: SyntaxError: No one parser could not parse file
    at ConfigResolver.<anonymous> (C:\Users\serge\.vscode\extensions\mrmlnc.vscode-postcss-sorting-2.3.0\node_modules\vscode-config-resolver\out\vcr.js:118:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\serge\.vscode\extensions\mrmlnc.vscode-postcss-sorting-2.3.0\node_modules\vscode-config-resolver\out\vcr.js:4:58)
e.onUnexpectedError @ shell.ts:443
(anonymous) @ shell.ts:403
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:139
t.onUnexpectedExtHostError @ mainThreadErrors.ts:13
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:275
f @ ipcRemoteCom.ts:231
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98

**Comment by ghost** [comment]
Well, I found out that if you don't have any config defined explicitly - it will fail. After setting config in settings.json, it started working.
I think this is a bug, because common practice is to use some default config.
At least, please add this to description, to save people's time.

**Comment by mrmlnc** [comment]
Related to https://github.com/mrmlnc/config-profiler/issues/4. I'll update plugin today/tomorrow 🎉
