### ISSUE TITLE
PostCSS Sorting doesn't work in VS code

### ISSUE THREAD

**Issue by NikolaySolodukhin** [mrmlnc/vscode-postcss-sorting#74]
A couple of weeks ago everything worked fine, but a couple of days ago such a command began to be displayed. Could you tell me what the problem is?

`command 'postcssSorting.sort' not found` 

 I have a file in the root of my project

.postcss-sorting.json.

**Comment by mrmlnc** [comment]
Oh, shit! I publish Major version as Minor 💃 

Sorry. I republish this extension today. Major changelog:

  * Command: `postcssSorting.sort` → `postcssSorting.execute`
  * Settings: `postcssSorting` → `postcssSorting.config`

**Comment by Eugene-Musika** [comment]
Still doesn't work.
![image](https://user-images.githubusercontent.com/19905407/31225227-c3aa7500-a9d9-11e7-8cc2-e92f5e38c19b.png)

video: 
[![Video bug](https://img.youtube.com/vi/ibDAX-zLCuA/0.jpg)](https://www.youtube.com/watch?v=ibDAX-zLCuA)

**Comment by mrmlnc** [comment]
@Eugene-Musika, it's works for me. You can give me your config and stylesheets (maybe minimal example)?

**Comment by Eugene-Musika** [comment]
Here you go
```json
{
  "files.autoSave": "onFocusChange",
  "files.trimTrailingWhitespace": true,
  "files.insertFinalNewline": true,
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/.DS_Store": true,
    "**/node_modules": true,
    "**/bower_components": true
  },
	"editor.tabSize": 2,
	"editor.wordWrap": "on",
	"workbench.activityBar.visible": true,
	"workbench.statusBar.visible": true,
  "window.zoomLevel": -0.5,
  "editor.fontSize": 14,
  "terminal.integrated.fontSize": 13,
  "editor.lineHeight": 20,
  "editor.fontFamily": "'Inconsolata LGC', Inconsolata, Menlo, Monaco, 'Courier New', monospace",
  "css.validate": false,
	"scss.validate": false,
  "sync.gist": "6a6e73074cf878ea236d00383173c8bc",
  "sync.lastUpload": "2017-09-04T15:20:27.653Z",
  "sync.lastDownload": "2017-09-05T15:54:11.979Z",
  "sync.anonymousGist": false,
  "eslint.autoFixOnSave": true,
  "todohighlight.exclude": [
    "**/node_modules/**",
    "**/bower_components/**",
    "**/dist/**",
    "**/build/**",
    "**/.vscode/**",
    "**/.github/**",
    "**/_output/**",
    "**/*.min.*",
    "**/*.map",
    "**/.next/**",
    "dist",
    ".git"
  ],
  "todohighlight.defaultStyle": {
    "color": "#000",
    "overviewRulerColor": "gray"
  },
  "todohighlight.keywords": [
    {
      "text": "NOTE:",
      "backgroundColor": "#ff0",
      "overviewRulerColor": "rgba(255, 255, 0, 0.7)"
    },{
      "text": "FUTURE:",
      "backgroundColor": "#0ff",
      "overviewRulerColor": "rgba(0, 255, 255, 0.7)"
      },{
        "text": "CHANGES:",
        "backgroundColor": "#eee",
        "overviewRulerColor": "rgba(255, 255, 255, 0.7)"
    },{
      "text": "TODO:",
      "color": "#000",
      "backgroundColor": "#99ff00",
      "overviewRulerColor": "rgba(150, 255, 0, 0.7)"
    },{
      "text": "FIXME:",
      "color": "#000",
      "backgroundColor": "#ff6e00",
      "overviewRulerColor": "rgba(255, 100, 0, 0.7)"
    }
  ],
  "workbench.editor.tabCloseButton": "off",
  "editor.snippetSuggestions": "top",
  "search.exclude": {
    "**/node_modules": true,
    "**/bower_components": true,
    "dist": true
  },
  "css_peek.activeLanguages": [
    "html",
    "ejs",
    "twig"
  ],
  "docthis.inferTypesFromNames": true,
  "htmlhint.options": {
    "doctype-first": false
  },
  "auto-close-tag.SublimeText3Mode": true,
  "git.confirmSync": false,
  "editor.tabCompletion": false,
  "stylelint.config": {
    "extends": "/Users/muse/Files/vscode_settings/.stylelintrc.json"
  },
  "sortImports.onSave": false,
  "eslint.options": {
    "configFile": "/Users/muse/Files/vscode_settings/.eslintrc.json"
  },
  "sync.autoDownload": false,
  "sync.autoUpload": false,
  "workbench.iconTheme": "vscode-great-icons",
  "sync.host": "",
  "sync.pathPrefix": "",
  "php.validate.executablePath": "/usr/bin/php",
  "editor.insertSpaces": false,
  "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
  "files.associations": {
    "*.jsx": "jsx",
    "*.har": "json"
  },
  "javascript.validate.enable": false,
  "editor.minimap.enabled": false,
  "git.enableSmartCommit": true,
  "extensions.autoUpdate": true,
  "vscode-exports-autocomplete.addSpacingAroundCurlyBraces": true,
  "better-comments.highlightColor": "#13884C",
  "better-comments.questionColor": "#2865e2",
  "emmet.triggerExpansionOnTab": true,
  "sync.quietSync": false,
  "sync.askGistName": false,
  "workbench.colorTheme": "Custom theme",
  "window.newWindowDimensions": "maximized",
  "postcssSorting.config": {
    "order": [
      "custom-properties",
			"dollar-variables",
			{
				"type": "at-rule",
				"name": "extend"
			},
			"declarations",
			"at-rules",
			"rules"
    ],
    "properties-order": [
      {
				"properties": [
					"position",
					"z-index",
					"top",
					"right",
					"bottom",
					"left"
				]
			},
			{
				"properties": [
					"display",
					"visibility",
					"float",
					"clear",
					"overflow",
					"overflow-x",
					"overflow-y",
					"-ms-overflow-x",
					"-ms-overflow-y",
					"clip",
					"zoom",
					"flex-direction",
					"flex-order",
					"flex-pack",
					"flex-align"
				]
			},
			{
				"properties": [
					"-webkit-box-sizing",
					"-moz-box-sizing",
					"box-sizing",
					"width",
					"min-width",
					"max-width",
					"height",
					"min-height",
					"max-height",
					"margin",
					"margin-top",
					"margin-right",
					"margin-bottom",
					"margin-left",
					"padding",
					"padding-top",
					"padding-right",
					"padding-bottom",
					"padding-left"
				]
			},
			{
				"properties": [
					"table-layout",
					"empty-cells",
					"caption-side",
					"border-spacing",
					"border-collapse",
					"list-style",
					"list-style-position",
					"list-style-type",
					"list-style-image"
				]
			},
			{
				"properties": [
					"content",
					"quotes",
					"counter-reset",
					"counter-increment",
					"resize",
					"cursor",
					"nav-index",
					"nav-up",
					"nav-right",
					"nav-down",
					"nav-left",
					"-webkit-transition",
					"-moz-transition",
					"-ms-transition",
					"-o-transition",
					"transition",
					"-webkit-transition-delay",
					"-moz-transition-delay",
					"-ms-transition-delay",
					"-o-transition-delay",
					"transition-delay",
					"-webkit-transition-timing-function",
					"-moz-transition-timing-function",
					"-ms-transition-timing-function",
					"-o-transition-timing-function",
					"transition-timing-function",
					"-webkit-transition-duration",
					"-moz-transition-duration",
					"-ms-transition-duration",
					"-o-transition-duration",
					"transition-duration",
					"-webkit-transition-property",
					"-moz-transition-property",
					"-ms-transition-property",
					"-o-transition-property",
					"transition-property",
					"-webkit-transform",
					"-moz-transform",
					"-ms-transform",
					"-o-transform",
					"transform",
					"-webkit-transform-origin",
					"-moz-transform-origin",
					"-ms-transform-origin",
					"-o-transform-origin",
					"transform-origin",
					"-webkit-animation",
					"-moz-animation",
					"-ms-animation",
					"-o-animation",
					"animation",
					"-webkit-animation-name",
					"-moz-animation-name",
					"-ms-animation-name",
					"-o-animation-name",
					"animation-name",
					"-webkit-animation-duration",
					"-moz-animation-duration",
					"-ms-animation-duration",
					"-o-animation-duration",
					"animation-duration",
					"-webkit-animation-play-state",
					"-moz-animation-play-state",
					"-ms-animation-play-state",
					"-o-animation-play-state",
					"animation-play-state",
					"-webkit-animation-timing-function",
					"-moz-animation-timing-function",
					"-ms-animation-timing-function",
					"-o-animation-timing-function",
					"animation-timing-function",
					"-webkit-animation-delay",
					"-moz-animation-delay",
					"-ms-animation-delay",
					"-o-animation-delay",
					"animation-delay",
					"-webkit-animation-iteration-count",
					"-moz-animation-iteration-count",
					"-ms-animation-iteration-count",
					"-o-animation-iteration-count",
					"animation-iteration-count",
					"-webkit-animation-iteration-count",
					"-moz-animation-iteration-count",
					"-ms-animation-iteration-count",
					"-o-animation-iteration-count",
					"animation-iteration-count",
					"-webkit-animation-direction",
					"-moz-animation-direction",
					"-ms-animation-direction",
					"-o-animation-direction",
					"animation-direction",
					"text-align",
					"-webkit-text-align-last",
					"-moz-text-align-last",
					"-ms-text-align-last",
					"text-align-last",
					"vertical-align",
					"white-space",
					"text-decoration",
					"text-emphasis",
					"text-emphasis-color",
					"text-emphasis-style",
					"text-emphasis-position",
					"text-indent",
					"-ms-text-justify",
					"text-justify",
					"text-transform",
					"letter-spacing",
					"word-spacing",
					"-ms-writing-mode",
					"text-outline",
					"text-transform",
					"text-wrap",
					"text-overflow",
					"-ms-text-overflow",
					"text-overflow-ellipsis",
					"text-overflow-mode",
					"-ms-word-wrap",
					"word-wrap",
					"word-break",
					"-ms-word-break",
					"-moz-tab-size",
					"-o-tab-size",
					"tab-size",
					"-webkit-hyphens",
					"-moz-hyphens",
					"hyphens",
					"pointer-events"
				]
			},
			{
				"properties": [
					"opacity",
					"filter:progid:DXImageTransform.Microsoft.Alpha(Opacity",
					"-ms-filter:'progid:DXImageTransform.Microsoft.Alpha",
					"-ms-interpolation-mode",
					"color",
					"border",
					"border-collapse",
					"border-width",
					"border-style",
					"border-color",
					"border-top",
					"border-top-width",
					"border-top-style",
					"border-top-color",
					"border-right",
					"border-right-width",
					"border-right-style",
					"border-right-color",
					"border-bottom",
					"border-bottom-width",
					"border-bottom-style",
					"border-bottom-color",
					"border-left",
					"border-left-width",
					"border-left-style",
					"border-left-color",
					"-webkit-border-radius",
					"-moz-border-radius",
					"border-radius",
					"-webkit-border-top-left-radius",
					"-moz-border-radius-topleft",
					"border-top-left-radius",
					"-webkit-border-top-right-radius",
					"-moz-border-radius-topright",
					"border-top-right-radius",
					"-webkit-border-bottom-right-radius",
					"-moz-border-radius-bottomright",
					"border-bottom-right-radius",
					"-webkit-border-bottom-left-radius",
					"-moz-border-radius-bottomleft",
					"border-bottom-left-radius",
					"-webkit-border-image",
					"-moz-border-image",
					"-o-border-image",
					"border-image",
					"-webkit-border-image-source",
					"-moz-border-image-source",
					"-o-border-image-source",
					"border-image-source",
					"-webkit-border-image-slice",
					"-moz-border-image-slice",
					"-o-border-image-slice",
					"border-image-slice",
					"-webkit-border-image-width",
					"-moz-border-image-width",
					"-o-border-image-width",
					"border-image-width",
					"-webkit-border-image-outset",
					"-moz-border-image-outset",
					"-o-border-image-outset",
					"border-image-outset",
					"-webkit-border-image-repeat",
					"-moz-border-image-repeat",
					"-o-border-image-repeat",
					"border-image-repeat",
					"outline",
					"outline-width",
					"outline-style",
					"outline-color",
					"outline-offset",
					"background",
					"filter:progid:DXImageTransform.Microsoft.AlphaImageLoader",
					"background-color",
					"background-image",
					"background-repeat",
					"background-attachment",
					"background-position",
					"background-position-x",
					"-ms-background-position-x",
					"background-position-y",
					"-ms-background-position-y",
					"background-clip",
					"background-origin",
					"background-size",
					"box-decoration-break",
					"-webkit-box-shadow",
					"-moz-box-shadow",
					"box-shadow",
					"-webkit-box-shadow",
					"-moz-box-shadow",
					"box-shadow",
					"-webkit-box-shadow",
					"-moz-box-shadow",
					"box-shadow",
					"-webkit-box-shadow",
					"-moz-box-shadow",
					"box-shadow",
					"filter:progid:DXImageTransform.Microsoft.gradient",
					"-ms-filter:'progid:DXImageTransform.Microsoft.gradient",
					"text-shadow"
				]
			},
			{
				"properties": [
					"font",
					"font-family",
					"font-size",
					"font-weight",
					"font-style",
					"font-variant",
					"font-size-adjust",
					"font-stretch",
					"font-effect",
					"font-emphasize",
					"font-emphasize-position",
					"font-emphasize-style",
					"font-smooth",
					"line-height"
				]
			}
    ]
  }
}
```

```scss
.signup-container {
	float: right;
	position: static;
	transform: none;
	margin-right: 0;
	display: inline-block;
	min-width: 400px;
	padding: 45px 70px 20px;
	text-align: center;
	font-size: 14px;
	letter-spacing: normal;
	width: 330px;

	@include breakpoint(small down) {
		z-index: 0;
		box-shadow: none;
		display: block;
		margin: 0 auto;
		min-width: 0;
		width: 100%;
		padding: 45px 0;
	}
	// @include breakpoint(500 down) {
	// 	min-width: 0;
	// 	width: 100%;
	// 	padding: 45px 0;
	// }
}
```

**Comment by mrmlnc** [comment]
@Eugene-Musika, well, you have error in your configuration:

```
postcss-sorting: properties-order: Array should contain strings only
```

My plugin can't catch this error. This is related to [`console.warn`](https://github.com/hudochenkov/postcss-sorting/blob/master/index.js#L19-L26). Issue for this https://github.com/hudochenkov/postcss-sorting/issues/71.

**Comment by Eugene-Musika** [comment]
But it worked fine before update

**Comment by mrmlnc** [comment]
It works before, because we use `postcss-sorting` with version `2.x.x` – now `3.x.x`.

**Comment by NikolaySolodukhin** [comment]
Could you update version in https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-postcss-sorting ? Thank you.

**Comment by mrmlnc** [comment]
@NikolaySolodukhin, yeap, done!

**Comment by NikolaySolodukhin** [comment]
@mrmlnc Could you help me? postSorting still doesn't work. My config: "postcssSorting.config": ".postcss-sorting.json"

**Comment by NikolaySolodukhin** [comment]
@mrmlnc Could help me ? PostCSSSorting still doesn't work. My config "postcssSorting.config": "getup/.postcss-sorting.json";

    "clean-empty-lines": true,
    "at-rule-nested-empty-line-before": [true, {
      "except": ["first-nested"]
    }],
    "declaration-empty-line-before": [true, {
      "except": ["after-declaration", "first-nested"],
      "ignore": ["after-comment", "after-declaration"]
    }],
    "rule-nested-empty-line-before": [true, {
      "except": ["first-nested"],
      "ignore": ["after-comment"]
    }],
    "order": [
        "custom-properties",
        {
            "type": "at-rule",
            "name": "mixin"
        },
        "declarations",
        "at-rules",
        "rules"
    ],
    "properties-order": [{
            "emptyLineBefore": true,
            "properties": [
                "content",
                "position",
                "top",
                "right",
                "bottom",
                "left",
                "z-index"
            ]
        },
        {
            "emptyLineBefore": true,
            "properties": [
                "display",
                "-webkit-flex",
                "-ms-flex",
                "flex",
                "-webkit-flex-grow",
                "flex-grow",
                "-webkit-flex-shrink",
                "flex-shrink",
                "-webkit-flex-basis",
                "flex-basis",
                "-webkit-flex-flow",
                "flex-flow",
                "-webkit-flex-direction",
                "-ms-flex-direction",
                "flex-direction",
                "-webkit-flex-wrap",
                "flex-wrap",
                "-webkit-justify-content",
                "justify-content",
                "-webkit-align-content",
                "align-content",
                "-webkit-align-items",
                "align-items",
                "-webkit-order",
                "-ms-flex-order",
                "order",
                "-webkit-align-self",
                "align-self",
                "float",
                "clear",
                "-webkit-box-sizing",
                "-moz-box-sizing",
                "box-sizing",
                "width",
                "min-width",
                "max-width",
                "height",
                "min-height",
                "max-height",
                "margin",
                "margin-top",
                "margin-right",
                "margin-bottom",
                "margin-left",
                "padding",
                "padding-top",
                "padding-right",
                "padding-bottom",
                "padding-left",
                "overflow",
                "-ms-overflow-x",
                "overflow-x",
                "-ms-overflow-y",
                "overflow-y",
                "-webkit-overflow-scrolling",
                "-ms-overflow-style"
            ]
        },
        {
            "emptyLineBefore": true,
            "properties": [
                "list-style",
                "list-style-position",
                "list-style-type",
                "list-style-image",
                "border-collapse",
                "border-spacing",
                "table-layout",
                "empty-cells",
                "caption-side",
                "font",
                "font-weight",
                "font-size",
                "line-height",
                "font-family",
                "vertical-align",
                "text-align",
                "direction",
                "color",
                "text-transform",
                "text-decoration",
                "font-style",
                "font-variant",
                "font-size-adjust",
                "font-stretch",
                "font-effect",
                "font-emphasize",
                "font-emphasize-position",
                "font-emphasize-style",
                "-webkit-font-smoothing",
                "-moz-osx-font-smoothing",
                "font-smooth",
                "-webkit-text-align-last",
                "-moz-text-align-last",
                "-ms-text-align-last",
                "text-align-last",
                "letter-spacing",
                "word-spacing",
                "white-space",
                "text-emphasis",
                "text-emphasis-color",
                "text-emphasis-style",
                "text-emphasis-position",
                "text-indent",
                "-ms-text-justify",
                "text-justify",
                "-ms-writing-mode",
                "text-outline",
                "text-wrap",
                "-ms-text-overflow",
                "text-overflow",
                "text-overflow-ellipsis",
                "text-overflow-mode",
                "text-orientation",
                "-ms-word-wrap",
                "word-wrap",
                "-ms-word-break",
                "word-break",
                "-moz-tab-size",
                "-o-tab-size",
                "overflow-wrap",
                "tab-size",
                "-webkit-hyphens",
                "-moz-hyphens",
                "hyphens",
                "unicode-bidi",
                "columns",
                "column-count",
                "column-fill",
                "column-gap",
                "column-rule",
                "column-rule-color",
                "column-rule-style",
                "column-rule-width",
                "column-span",
                "column-width",
                "text-shadow",
                "page-break-after",
                "page-break-before",
                "page-break-inside",
                "src"
            ]
        },
        {
            "emptyLineBefore": true,
            "properties": [
                "background",
                "background-color",
                "background-image",
                "background-repeat",
                "background-position",
                "-ms-background-position-x",
                "background-position-x",
                "-ms-background-position-y",
                "background-position-y",
                "-webkit-background-size",
                "-moz-background-size",
                "-o-background-size",
                "background-size",
                "-webkit-background-clip",
                "-moz-background-clip",
                "background-clip",
                "background-origin",
                "background-attachment",
                "box-decoration-break",
                "background-blend-mode",
                "border",
                "border-width",
                "border-style",
                "border-color",
                "border-top",
                "border-top-width",
                "border-top-style",
                "border-top-color",
                "border-right",
                "border-right-width",
                "border-right-style",
                "border-right-color",
                "border-bottom",
                "border-bottom-width",
                "border-bottom-style",
                "border-bottom-color",
                "border-left",
                "border-left-width",
                "border-left-style",
                "border-left-color",
                "-webkit-border-radius",
                "-moz-border-radius",
                "border-radius",
                "-webkit-border-top-left-radius",
                "-moz-border-radius-topleft",
                "border-top-left-radius",
                "-webkit-border-top-right-radius",
                "-moz-border-radius-topright",
                "border-top-right-radius",
                "-webkit-border-bottom-right-radius",
                "-moz-border-radius-bottomright",
                "border-bottom-right-radius",
                "-webkit-border-bottom-left-radius",
                "-moz-border-radius-bottomleft",
                "border-bottom-left-radius",
                "-webkit-border-image",
                "-moz-border-image",
                "-o-border-image",
                "border-image",
                "-webkit-border-image-source",
                "-moz-border-image-source",
                "-o-border-image-source",
                "border-image-source",
                "-webkit-border-image-slice",
                "-moz-border-image-slice",
                "-o-border-image-slice",
                "border-image-slice",
                "-webkit-border-image-width",
                "-moz-border-image-width",
                "-o-border-image-width",
                "border-image-width",
                "-webkit-border-image-outset",
                "-moz-border-image-outset",
                "-o-border-image-outset",
                "border-image-outset",
                "-webkit-border-image-repeat",
                "-moz-border-image-repeat",
                "-o-border-image-repeat",
                "border-image-repeat",
                "outline",
                "outline-width",
                "outline-style",
                "outline-color",
                "outline-offset",
                "-webkit-box-shadow",
                "-moz-box-shadow",
                "box-shadow",
                "-webkit-transform",
                "-moz-transform",
                "-ms-transform",
                "-o-transform",
                "transform",
                "-webkit-transform-origin",
                "-moz-transform-origin",
                "-ms-transform-origin",
                "-o-transform-origin",
                "transform-origin",
                "-webkit-backface-visibility",
                "-moz-backface-visibility",
                "backface-visibility",
                "-webkit-perspective",
                "-moz-perspective",
                "perspective",
                "-webkit-perspective-origin",
                "-moz-perspective-origin",
                "perspective-origin",
                "-webkit-transform-style",
                "-moz-transform-style",
                "transform-style",
                "visibility",
                "cursor",
                "opacity",
                "-webkit-filter",
                "filter",
                "backdrop-filter"
            ]
        },
        {
            "emptyLineBefore": true,
            "properties": [
                "-webkit-transition",
                "-moz-transition",
                "-ms-transition",
                "-o-transition",
                "transition",
                "-webkit-transition-delay",
                "-moz-transition-delay",
                "-ms-transition-delay",
                "-o-transition-delay",
                "transition-delay",
                "-webkit-transition-timing-function",
                "-moz-transition-timing-function",
                "-ms-transition-timing-function",
                "-o-transition-timing-function",
                "transition-timing-function",
                "-webkit-transition-duration",
                "-moz-transition-duration",
                "-ms-transition-duration",
                "-o-transition-duration",
                "transition-duration",
                "-webkit-transition-property",
                "-moz-transition-property",
                "-ms-transition-property",
                "-o-transition-property",
                "transition-property",
                "-webkit-animation",
                "-moz-animation",
                "-ms-animation",
                "-o-animation",
                "animation",
                "-webkit-animation-name",
                "-moz-animation-name",
                "-ms-animation-name",
                "-o-animation-name",
                "animation-name",
                "-webkit-animation-duration",
                "-moz-animation-duration",
                "-ms-animation-duration",
                "-o-animation-duration",
                "animation-duration",
                "-webkit-animation-play-state",
                "-moz-animation-play-state",
                "-ms-animation-play-state",
                "-o-animation-play-state",
                "animation-play-state",
                "-webkit-animation-timing-function",
                "-moz-animation-timing-function",
                "-ms-animation-timing-function",
                "-o-animation-timing-function",
                "animation-timing-function",
                "-webkit-animation-delay",
                "-moz-animation-delay",
                "-ms-animation-delay",
                "-o-animation-delay",
                "animation-delay",
                "-webkit-animation-iteration-count",
                "-moz-animation-iteration-count",
                "-ms-animation-iteration-count",
                "-o-animation-iteration-count",
                "animation-iteration-count",
                "-webkit-animation-direction",
                "-moz-animation-direction",
                "-ms-animation-direction",
                "-o-animation-direction",
                "animation-direction",
                "-webkit-animation-fill-mode",
                "-moz-animation-fill-mode",
                "-ms-animation-fill-mode",
                "-o-animation-fill-mode",
                "animation-fill-mode"
            ]
        },
        {
            "emptyLineBefore": true,
            "properties": [
                "appearance",
                "clip",
                "clip-path",
                "counter-reset",
                "counter-increment",
                "resize",
                "-webkit-user-select",
                "-moz-user-select",
                "-ms-user-select",
                "user-select",
                "-webkit-tap-highlight-color",
                "nav-index",
                "nav-up",
                "nav-right",
                "nav-down",
                "nav-left",
                "pointer-events",
                "quotes",
                "touch-action",
                "will-change",
                "zoom"
            ]
        },
        {
            "emptyLineBefore": true,
            "properties": [
              "fill",
              "fill-rule",
              "clip-rule",
              "stroke"
            ]
        }
    ],
    "unspecified-properties-position": "bottom"

**Comment by mrmlnc** [comment]
@NikolaySolodukhin, please, read this [migration guide](https://github.com/hudochenkov/postcss-sorting#migration-from-2x).

**Comment by crown3** [comment]
@NikolaySolodukhin Maybe you are using 3.x ...

[postcss sorting config](https://github.com/hudochenkov/postcss-sorting)

![image](https://user-images.githubusercontent.com/19649900/38967567-2f0ab8d0-43ba-11e8-978d-c682fd278232.png)

**Comment by Roman9961** [comment]
@NikolaySolodukhin set
 "properties-order": "alphabetical",

**Comment by nicogaldo** [comment]
Hello everyone, I come to revive a dead thread. What about the breakpoint between the properties? Has this function been lost?

Ej:
```
// Sort properties in particular order.
    "sort-order": [
        [
            "position",
            "top",
            "right",
            "bottom",
            "left",
            "z-index"
        ],
        [
            "display",
            "visibility",
            "float",
            "width",
            "height",
            "max-width",
            "max-height",
            "min-width",
            "min-height",
            "padding",
            "padding-top",
           ...
```

```
.swiper-button-next,
.swiper-button-prev {
    top: calc(25% - 22px);
    bottom: 0;

    width: 60px;
    height: 60px;

    transition: all .6s ease;
    border-radius: 50%;
    background: rgba(255,255,255,.5);

    &:after {
        font-size: 2em;

        color: $primary;
    }

    &:hover {
        background: white;
    }
}
```

**Comment by ebrahimiaval** [comment]
I fixed this issue by set configs of vscode-postcss-sorting in to setting.json of vscode. when i set configs it in to postcss.config.js not work.

```
//in vscode setting.json
{
 "postcssSorting.config": {
        "properties-order": "alphabetical"
    }
}
```

**Comment by Pixel48** [comment]
It sorts by sorting preferences after installing [Sass](https://marketplace.visualstudio.com/items?itemName=Syler.sass-indented) extension with this config
```json
"postcssSorting.config": {
    "order": [
      "custom-properties",
      "dollar-variables",
      "declarations",
      "at-rules",
      "rules"
    ],
    "properties-order": [
      "display",
      "position",
      "top",
      "right",
      "bottom",
      "left"
    ]
  },
```
> You may want to set default scss formatter:
```json
"[scss]": {
    "editor.defaultFormatter": "mrmlnc.vscode-postcss-sorting"
  },
```
