### ISSUE TITLE
No Sorting Occurs

### ISSUE THREAD

**Issue by tohuw** [mrmlnc/vscode-postcss-sorting#75]
I'm unable to get this plugin to do anything, and no output is furnished to the debug or output consoles that helps. I have postcss-sorting installed (via `npm i -g postcss-sorting`), but nothing is sorted on any of my css files.

Plugin: v3.0.0
postcss-sorting: 3.0.2
VSCode: 1.17.0

**Comment by mrmlnc** [comment]
I trying to format with my config and it's perfectly works. You can provide more information about your workflow (OS, set of extensions and your CSS file (maybe small example))?

**Comment by tohuw** [comment]
macOS 10.12.6

Extensions:

    DavidAnson.vscode-markdownlint-0.10.1
    chenxsan.vscode-standardjs-1.2.0
    eamodio.gitlens-5.5.0
    mhmadhamster.postcss-language-2.0.2
    robertohuertasm.vscode-icons-7.15.0
    EditorConfig.editorconfig-0.10.1
    christian-kohler.npm-intellisense-1.3.0 eg2.vscode-npm-script-0.2.1
    mrmlnc.vscode-postcss-sorting-3.0.0
    tanato.vscode-gulp-0.0.4
    apazureck.gulpsymbols-0.1.1
    donjayamanne.python-0.7.0
    formulahendry.auto-close-tag-0.5.1
    ms-vscode.powershell-1.4.3
    wholroyd.jinja-0.0.8
    bierner.color-info-0.5.0
    eamodio.gitlens-5.4.1
    helixquar.randomeverything-0.0.3
    robertohuertasm.vscode-icons-7.14.0

Also tried it with all extensions disabled except this one.

Here's an example css file that does not sort:

    body {
        background-color: red;
        font-size: 1em;
        margin-right: 2rem;
        line-height: 4;
        border: 1px solid purple;
    }

Thanks for the help!

**Comment by tohuw** [comment]
Also, I've nothing pertaining to this plugin in my settings. I'm just trying with the defaults.

    {
        "workbench.iconTheme": "vscode-icons",
        "files.autoSave": "onFocusChange",
        "editor.fontFamily": "Hack, Menlo, Monaco, 'Courier New', monospace",
        "editor.renderWhitespace": "boundary",
        "editor.wordWrap": "on",
        "editor.scrollBeyondLastLine": false,
        "editor.smoothScrolling": true,
        "editor.acceptSuggestionOnEnter": "off",
        "editor.cursorBlinking": "phase",
        "editor.fontLigatures": true,
        "workbench.editor.tabCloseButton": "left",
        "workbench.startupEditor": "none",
        "window.restoreWindows": "folders",
        "window.restoreFullscreen": true,
        "window.closeWhenEmpty": true,
        "window.titleBarStyle": "native",
        "window.nativeTabs": true,
        "files.trimTrailingWhitespace": true,
        "explorer.openEditors.visible": 0,
        "terminal.external.osxExec": "iterm.app",
        "git.enableCommitSigning": false,
        "workbench.colorTheme": "Monokai Dimmed",
        "gitlens.codeLens.enabled": false,
        "editor.fontSize": 13,
        "standard.enable": true,
        "editor.parameterHints": false,
        "files.associations": {
            "*.css": "postcss"
        },
        "window.zoomLevel": 0,
        "vsicons.dontShowNewVersionMessage": true
    }

**Comment by tohuw** [comment]
I now wonder if my problem is upstream, or at least how to test this quickly... I opened [an issue against postcss-sorting](https://github.com/hudochenkov/postcss-sorting/issues/72) to ask about testing via CLI. It'd be helpful to know if this was the plugin or postcss-sorting itself...

**Comment by mrmlnc** [comment]
You try to use https://github.com/mrmlnc/vscode-postcss-sorting#options? Now we has no support for `.postcssrc.json` file.

**Comment by tohuw** [comment]
Yep, now my VSCode Settings is:

    {
        "workbench.iconTheme": "vscode-icons",
        "files.autoSave": "onFocusChange",
        "editor.fontFamily": "Hack, Menlo, Monaco, 'Courier New', monospace",
        "editor.renderWhitespace": "boundary",
        "editor.wordWrap": "on",
        "editor.scrollBeyondLastLine": false,
        "editor.smoothScrolling": true,
        "editor.acceptSuggestionOnEnter": "off",
        "editor.cursorBlinking": "phase",
        "editor.fontLigatures": true,
        "workbench.editor.tabCloseButton": "left",
        "workbench.startupEditor": "none",
        "window.restoreWindows": "folders",
        "window.restoreFullscreen": true,
        "window.closeWhenEmpty": true,
        "window.titleBarStyle": "native",
        "window.nativeTabs": true,
        "files.trimTrailingWhitespace": true,
        "explorer.openEditors.visible": 0,
        "terminal.external.osxExec": "iterm.app",
        "git.enableCommitSigning": false,
        "workbench.colorTheme": "Monokai Dimmed",
        "gitlens.codeLens.enabled": false,
        "editor.fontSize": 13,
        "standard.enable": true,
        "editor.parameterHints": false,
        "files.associations": {
            "*.css": "postcss"
        },
        "window.zoomLevel": 0,
        "vsicons.dontShowNewVersionMessage": true,
        "postcssSorting.config": {
            "order": [
            "custom-properties",
            "dollar-variables",
            "declarations",
            "at-rules",
            "rules"
            ],
            "properties-order": ["display", "position", "top", "right", "bottom", "left"]
        }
    }

Still nothing happens when I try to sort.

**Comment by mrmlnc** [comment]
I add `	display: block;` to your CSS and run plugin with your settings. Works fine for me.

![qwe](https://user-images.githubusercontent.com/7034281/31352351-2361cc22-ad37-11e7-8cfc-8f32463cc104.gif)

**Comment by tohuw** [comment]
I guess I'd better learn how to read the clearly spelled out options... of course the previous contents wouldn't sort; I didn't provide an order for those elements. Thanks a bunch! Looks like it's doing its job now; I just need to write more statements in `properties-order` to get what I want.
