### ISSUE TITLE
Concentric CSS Config

### ISSUE THREAD

**Issue by softshape** [mrmlnc/vscode-postcss-sorting#79]
The plugin itself has empty config and so is not usable right after installation. Here's a Concentric CSS based config you can add to user configuration (https://github.com/brandon-rhodes/Concentric-CSS/).

> "postcssSorting.config": {
  "order": [
    "custom-properties",
    "dollar-variables",
    "declarations",
    "at-rules",
    "rules"
  ],
  "properties-order": [
    // based on Concentric CSS https://github.com/brandon-rhodes/Concentric-CSS/
    "box-sizing",
    "display",
    "position",
    "top",
    "right",
    "bottom",
    "left",
    "float",
    "clear",
    "align-content",
    "align-items",
    "align-self",
    "flex",
    "flex-basis",
    "flex-direction",
    "flex-flow",
    "flex-grow",
    "flex-shrink",
    "flex-wrap",
    "justify-content",
    "order",
    "columns",
    "column-gap",
    "column-fill",
    "column-rule",
    "column-rule-width",
    "column-rule-style",
    "column-rule-color",
    "column-span",
    "column-count",
    "column-width",
    "visibility",
    "opacity",
    "z-index",
    "margin",
    "margin-top",
    "margin-right",
    "margin-bottom",
    "margin-left",
    "width",
    "min-width",
    "max-width",
    "height",
    "min-height",
    "max-height",
    "outline",
    "outline-offset",
    "outline-width",
    "outline-style",
    "outline-color",
    "border",
    "border-top",
    "border-right",
    "border-bottom",
    "border-left",
    "border-width",
    "border-top-width",
    "border-right-width",
    "border-bottom-width",
    "border-left-width",
    "border-style",
    "border-top-style",
    "border-right-style",
    "border-bottom-style",
    "border-left-style",
    "border-radius",
    "border-top-left-radius",
    "border-top-right-radius",
    "border-bottom-left-radius",
    "border-bottom-right-radius",
    "border-color",
    "border-top-color",
    "border-right-color",
    "border-bottom-color",
    "border-left-color",
    "border-image",
    "border-image-source",
    "border-image-width",
    "border-image-outset",
    "border-image-repeat",
    "border-image-slice",
    "box-shadow",
    "background",
    "background-attachment",
    "background-clip",
    "background-color",
    "background-image",
    "background-origin",
    "background-position",
    "background-repeat",
    "background-size",
    "stroke",
    "fill",
    "padding",
    "padding-top",
    "padding-right",
    "padding-bottom",
    "padding-left",
    "overflow",
    "overflow-x",
    "overflow-y",
    "resize",
    "cursor",
    "list-style",
    "list-style-type",
    "list-style-position",
    "list-style-image",
    "caption-side",
    "table-layout",
    "border-collapse",
    "border-spacing",
    "empty-cells",
    "-webkit-backface-visibility",
    "backface-visibility",
    "perspective",
    "perspective-origin",
    "-webkit-transform",
    "-moz-transform",
    "-o-transform",
    "transform",
    "-webkit-transform-origin",
    "transform-origin",
    "transform-style",
    "transition",
    "transition-delay",
    "transition-duration",
    "transition-property",
    "transition-timing-function",
    "-webkit-filter",
    "filter",
    "-webkit-animation",
    "-moz-animation",
    "-ms-animation",
    "-o-animation",
    "animation",
    "animation-name",
    "animation-duration",
    "animation-timing-function",
    "animation-delay",
    "animation-iteration-count",
    "animation-direction",
    "animation-fill-mode",
    "animation-play-state",
    "vertical-align",
    "direction",
    "tab-size",
    "text-align",
    "text-align-last",
    "text-justify",
    "text-indent",
    "text-transform",
    "text-decoration",
    "text-decoration-color",
    "text-decoration-line",
    "text-decoration-style",
    "text-rendering",
    "text-shadow",
    "text-overflow",
    "line-height",
    "word-spacing",
    "letter-spacing",
    "white-space",
    "word-break",
    "word-wrap",
    "color",
    "font",
    "font-family",
    "font-size",
    "font-size-adjust",
    "font-stretch",
    "font-weight",
    "font-smoothing",
    "osx-font-smoothing",
    "font-variant",
    "font-style",
    "content",
    "quotes",
    "counter-reset",
    "counter-increment",
    "page-break-before",
    "page-break-after",
    "page-break-inside",
    "-webkit-user-select",
    "-khtml-user-select",
    "-moz-user-select",
    "-ms-user-select",
    "user-select",
    "pointer-events",
    "-webkit-appearance"  
  ]
}

**Comment by mrmlnc** [comment]
Each user must configure his instrument. You can create your own config (see https://github.com/mrmlnc/vscode-postcss-sorting#options) and share it within other users.
